### ISSUE TITLE
Redirect URL assumes the local port is the same as the exposed port

### ISSUE THREAD

**Issue by rprieto** [authelia/oidc-tester-app#8]
Hi, thank you for open-sourcing this project.

I am facing an issue when running it behind a reverse proxy.
The following code assumes that the port we listen on is the same as the publically exposed port:

```go
options.RedirectURL = fmt.Sprintf("%s://%s:%d/oauth2/callback", options.RedirectScheme, options.RedirectDomain, options.Port)
```

When running on Kubernetes for example, it's common to listen on port 8080 but actually be reachable on port 443 (TLS terminated by the router).

Is it possible to add a configuration for the public port, similar to how we can configure the scheme?
Thanks

**Comment by james-d-elliott** [comment]
I just saw this now, I'll take a look this week, sorry this was not our focus and it's been a busy few months with webauthn.

I think the answer is to replace the two args for redirect scheme and domain with a single, and keep port as just the port to listen on. Then we can just parse the new arg (--public-url) with url.Parse and build the url like that.

**Comment by james-d-elliott** [comment]
@rprieto pretty sure that solved it, let me know. It removes a whole lot of old options and replaces them with --public-url

Please let me know if the src doesn't explain it perfectly.
